"""empty message

Revision ID: 58d72554ee1e
Revises: 6a27051fd05f
Create Date: 2017-03-15 16:19:26.109846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58d72554ee1e'
down_revision = '6a27051fd05f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('user_id', sa.String(length=50), nullable=False))
    op.drop_constraint(u'user_profile_id_key', 'user_profile', type_='unique')
    op.create_unique_constraint(None, 'user_profile', ['user_id'])
    op.drop_column('user_profile', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('id', sa.INTEGER(), nullable=False))
    op.drop_constraint(None, 'user_profile', type_='unique')
    op.create_unique_constraint(u'user_profile_id_key', 'user_profile', ['id'])
    op.drop_column('user_profile', 'user_id')
    # ### end Alembic commands ###
